name: Обновление зависимостей
description: Обновляет зависимости в файле packagedef и создает Pull Request с изменениями

inputs:
  filter:
    description: Фильтр пакетов по именам (через запятую или пробел), шаблону (*, ?) или регулярному выражению
    required: false
  target:
    description: Тип целевой версии (latest, minor, patch)
    required: false
    default: latest
  message-prefix:
    description: Префикс для сообщения коммита и заголовка Pull Request
    required: false
  token:
    description: Токен для создания Pull Request
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Актуализация
      uses: actions/checkout@v5.0.0
      
    - name: Установка свойств git
      shell: bash
      run: |
        git config --global core.autocrlf true

    - name: Установка OneScript
      uses: otymko/setup-onescript@v1.5.1
      with:
        version: stable

    - name: Обновление зависимостей в packagedef
      uses: Stivo182/test/upgrade@main
      with:
        filter: ${{ inputs.filter }}
        target: ${{ inputs.target }}
        output: packages.json

    - name: Проверка наличия изменений
      id: check-changes
      shell: bash
      run: |
        if git diff --name-only | grep -E '^packagedef$'; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi    

    - name: Подготовка Pull Request
      if: steps.check-changes.outputs.has_changes == 'true'
      id: format-output
      shell: bash
      run: |
        # Формируем заголовок PR
        title=$(jq -r '
          (if "${{ inputs.message-prefix }}" != "" 
             then "${{ inputs.message-prefix }}: " 
             else "" 
           end) +
          "Bump " +
          (.[0:2] 
             | map("\(.packageName) \(.minVersionBefore) → \(.minVersionAfter)") 
             | join(", ")
          ) +
          (if length > 2 
             then " and \(length - 2) more package" + 
                (if length - 2 > 1 then "s" else "" end) 
             else "" 
           end)
        ' packages.json)
        echo "title=$title" >> $GITHUB_OUTPUT

        # Формируем тело PR
        {
          echo "body<<EOF"
          jq -r '
            .[] 
            | "- **\(.packageName)**: \(.minVersionBefore) → \(.minVersionAfter)\n" +
              "([repo](https://github.com/oscript-library/\(.packageName)) · " +
              "[hub](https://hub.oscript.io/package/\(.packageName)))"
          ' packages.json
          echo "EOF"
        } >> $GITHUB_OUTPUT

    - name: Создание Pull Request
      if: steps.check-changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.token }}
        title: ${{ steps.format-output.outputs.title }}
        commit-message: ${{ steps.format-output.outputs.title }}
        body: ${{ steps.format-output.outputs.body }}
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        add-paths: packagedef
        branch: depos/bump-deps/${{ inputs.target }}
        delete-branch: true
        labels: dependencies