name: Обновление зависимостей

on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Фильтр пакетов'
      target:
        description: 'Тип версии'
        default: 'latest'
        type: choice
        options:
          - latest
          - minor
          - patch

jobs:
  deps-upgrade:
    runs-on: ubuntu-latest
    env:
      MIN_OPM_VERSION: 1.3.0

    steps:
      - name: Актуализация
        uses: actions/checkout@v5.0.0

      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.5.1
        with:
          version: stable 

      - name: Проверка и установка opm
        run: |
          if command -v opm >/dev/null 2>&1; then
            v=$(opm -v | grep -oP '\d+\.\d+\.\d+')
            if [[ "$(printf '%s\n' "$v" "$MIN_OPM_VERSION" | sort -V | head -n1)" != "$MIN_OPM_VERSION" ]]; then
              opm install opm
            fi
          else
            opm install opm
          fi
          opm -v

      - name: Обновление зависимостей
        uses: Stivo182/test/upgrade@main
        with:
          filter: ${{ inputs.filter }}
          target: ${{ inputs.target }}