name: Обновление зависимостей

on:
  workflow_dispatch:
    inputs:
      filter:
        description: Фильтр пакетов
      target:
        description: Тип версии
        default: latest
        type: choice
        options:
          - latest
          - minor
          - patch

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Обновление зависимостей
        uses: Stivo182/depos-action@main
        with:
          filter: ${{ inputs.filter }}
          target: ${{ inputs.target }}
          message-prefix: build(deps) 