name: Обновление зависимостей

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      filter:
        description: 'Фильтр пакетов'
      target:
        description: 'Тип версии'
        default: 'latest'
        type: choice
        options:
          - latest
          - minor
          - patch

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    uses: Stivo182/test/.github/workflows/update-dependencies.yml@main
    with:
      filter: ${{ inputs.filter }}
      target: ${{ inputs.target }