name: Обновление зависимостей

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    uses: Stivo182/test/.github/workflows/update-dependencies.yml@main