name: Обновление зависимостей

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    uses: Stivo182/test/.github/workflows/update-dependencies.yml@main