name: Обновление зависимостей и создание PR
on: 
  workflow_call:
    inputs:
      filter:
        description: 'Фильтр пакетов по именам (через запятую или пробел), шаблону (*, ?) или регулярному выражению'
        required: false
        type: string
      target:
        description: 'Тип целевой версии (latest, minor, patch)'
        required: false
        type: string
        default: 'latest'
      message-prefix:
        description: 'Префикс для сообщения коммита'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write
  
jobs:
  deps-upgrade-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Актуализация
        uses: actions/checkout@v5.0.0

      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.5.1
        with:
          version: stable 

      - name: Обновление зависимостей в packagedef
        uses: Stivo182/test/upgrade@main
        with:
          filter: ${{ inputs.filter }}
          target: ${{ inputs.target }}
          output: packages.json

      - name: Проверка наличия изменений
        id: check-changes
        run: |
          if git diff --name-only | grep -E '^packagedef$'; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Формирование title и body
        if: steps.check-changes.outputs.changes_detected == 'true'
        id: format-output
        run: |
          # Title
          title=$(jq -r '
            (if "${{ inputs.message-prefix }}" != "" then "${{ inputs.message-prefix }}: " else "" end) +
            "Bump " + 
            (.[0:2] | map("\(.packageName) \(.minVersionBefore) → \(.minVersionAfter)") | join(", ")) + 
            (if length > 2 then 
              " and \(length - 2) more package" + (if length - 2 > 1 then "s" else "" end) 
            else "" end)
          ' packages.json)
          echo "title=$title" >> $GITHUB_OUTPUT

          # Body
          echo "body<<EOF" >> $GITHUB_OUTPUT
          jq -r '.[] | "- **\(.packageName)**: \(.minVersionBefore) → \(.minVersionAfter) \n([repo](https://github.com/oscript-library/\(.packageName)) · [hub](https://hub.oscript.io/package/\(.packageName)))"' packages.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Создание PR
        if: steps.check-changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          title: ${{ steps.format-output.outputs.title }}
          commit-message: ${{ steps.format-output.outputs.title }}
          body: ${{ steps.format-output.outputs.body }}
          add-paths: packagedef
          branch: depos/bump-deps/${{ inputs.target }}
          delete-branch: true
          labels: dependencies