name: Обновление зависимостей по запросу

on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Фильтр пакетов'
      target:
        description: 'Тип версии'
        default: 'latest'
        type: choice
        options:
          - latest
          - minor
          - patch

permissions:
  contents: write
  pull-requests: write

jobs:
  deps-upgrade-pr:
    uses: Stivo182/test/.github/workflows/deps-upgrade-pr.yml@main
    with:
      filter: ${{ inputs.filter }}
      target: ${{ inputs.target }}
      message-prefix: build(deps) 