name: Обновление зависимостей
on: 
  workflow_call:
    inputs:
      filter:
        description: 'Фильтр пакетов по именам (через запятую или пробел), шаблону (*, ?) или регулярному выражению'
        required: false
        type: string
      target:
        description: 'Тип целевой версии (latest, minor, patch)'
        required: false
        type: string
        default: 'latest'
  workflow_dispatch:
    inputs:
      filter:
        description: 'Фильтр пакетов'
      target:
        description: 'Тип версии'
        default: 'latest'
        type: choice
        options:
          - latest
          - minor
          - patch

permissions:
  contents: write
  pull-requests: write
  
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Актуализация
        uses: actions/checkout@v5.0.0

      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.5.1
        with:
          version: stable 

      - name: Установка depos
        run: |
          opm install opm
          opm install depos

      - name: Обновление зависимостей
        id: depos-upgrade
        run: |
          cmd="depos upgrade"
          [[ -n "${{ inputs.filter }}" ]] && cmd="$cmd -f '${{ inputs.filter }}'"
          [[ -n "${{ inputs.target }}" ]] && cmd="$cmd -t ${{ inputs.target }}"
          echo "depos_output<<EOF" >> $GITHUB_OUTPUT
          eval $cmd 2>&1 | sed '1d;$d' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Проверка наличия изменений
        id: check-changes
        run: |
          if git diff --name-only | grep -E '^packagedef$'; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Создание PR
        if: steps.check-changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Обновление зависимостей"
          commit-message: "Обновление зависимостей"
          body: ${{ steps.depos-upgrade.outputs.depos_output }}
          add-paths: packagedef
          branch: depos/update-dependencies
          delete-branch: true
          labels: dependencies, github_actions